[build]
builder = "nixpacks"
buildCommand = "rm -rf node_modules/.cache || true && npm install --force && npm run build && cd server && npm install && npm run build"

[deploy]
startCommand = "cd server && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
PORT = "$PORT"
CORAL_API_URL = "$CORAL_API_URL"
CORAL_SOCKET_URL = "$CORAL_SOCKET_URL"
NIXPACKS_NODE_VERSION = "20"