[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build && cd server && npm ci && npm run build"

[deploy]
startCommand = "cd server && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[env]
NODE_ENV = "production"
PORT = "$PORT"
CORAL_API_URL = "$CORAL_API_URL"
CORAL_SOCKET_URL = "$CORAL_SOCKET_URL"