[build]
builder = "nixpacks"
buildCommand = "cd server && npm run build"

[deploy]
startCommand = "cd server && npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "$PORT"