version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3002:3002"
    environment:
      - API_BASE_URL=http://host.docker.internal:3001/api
      - API_USERNAME=test@example.com
      - API_PASSWORD=password123
      - MCP_PORT=3002
    restart: unless-stopped
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge